### ISSUE TITLE
please add !include option

### ISSUE THREAD

**Issue by Mariusthvdb** [marcelveldt/hass-area-views#1]
trying to use an include:
```
  - path: default_view
    title: Ruimtes overzicht
    icon: mdi:view-grid
    cards:
      - !include /config/lovelace/includes/include_person_badge_card.yaml
```

results in:
<img width="603" alt="Schermafbeelding 2022-01-10 om 09 40 08" src="https://user-images.githubusercontent.com/33354141/148738068-3555d2b8-b423-4e67-89e9-c6fd2ca45a9b.png">

while this is the accepted yaml throughout?

---
btw, since this is the first issue in this repo:

THANKS for creating this, really very very nice, having a lot of fun with it already, and I expect we haven't seen the end of its development ;-)
